name: Build and Publish Docker Image

on:
  push:
    branches:
      main

  pull_request:
    branches:
      - main  # Change this to the branch you want to trigger the workflow
      
  # Allows you to run the workflow manually from the git actions tab
  workflow_dispatch:

jobs:

  generate-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Github Tag Bump
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ##INITIAL_VERSION: 1.0.0
        ##DEFAULT_BUMP: minor
    outputs:
      new_version: ${{ steps.tab_bump.ouputs.new_tag }}

  build:
    runs-on: ubuntu-latest
    needs: generate-version

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and tag Docker image
      run: |
        docker build -t aoidev2022/weatherforecast:${{ needs.generate-version.outputs.new_version }} .

    - name: Push Docker image to Docker Hub
      run: |
        docker push aoidev2022/weatherforecast:${{ needs.generate-version.outputs.new_version }}

    - name: Logout from Docker Hub
      run: docker logout
      
