# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - weatherforecast-aoi

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow
  
  workflow_dispatch: # Allows you to run the workflow manually from the git actions tab

jobs:
  generate-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Github Tag Bump
      id: tab_bump
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: true
        
    outputs:
      new_version: ${{ steps.tab_bump.outputs.new_tag }}
      
  build:
    runs-on: ubuntu-latest
    needs: generate-version

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        build-args: |
            "TAG=${{ needs.generate-version.outputs.new_version }}"
            "ASPNETCORE_ENVIRONMENT=${{ vars.ASPNETCORE_ENVIRONMENT }}"
            "SimpleProperty='apple'"
        push: true
        tags: index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/weatherforecast:${{ needs.generate-version.outputs.new_version }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - build 
      - generate-version
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: weatherforecast-aoi
        slot-name: production
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d55d7115427741ce96a71e8cf419bcf5 }}
        images: index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/weatherforecast:${{ needs.generate-version.outputs.new_version }}
