# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - weatherforecast-aoi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKERHUB_USERNAME }} ##${{ secrets.AzureAppService_ContainerUsername_75d4c390d8b941f091f6d9e6e9ceefb4 }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }} ##${{ secrets.AzureAppService_ContainerPassword_9a1875878746423bad75ea3fc6283fe8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/weatherforecast:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'weatherforecast-aoi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d55d7115427741ce96a71e8cf419bcf5 }}
        images: 'index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/weatherforecast:${{ github.sha }}'
